language: java
dist: trusty
install: skip

env:
  - TEMPLATE=bobcat-bdd
  - TEMPLATE=bobcat-junit5
  - TEMPLATE=bobcat-appium
  - TEMPLATE=bobcat-aem-bdd
  - TEMPLATE=bobcat-aem-junit

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./generate_and_test.sh
